kind = "web"
previewPath = "/"
title = "Smart Time Education"
version = "1.0.0"
id = "artifacts/smart-time"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/api", "/" ]
localPort = 22168

[services.development]
run = "pnpm --filter @workspace/smart-time run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/smart-time", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/smart-time", "run", "start" ]

[services.env]
PORT = "22168"
BASE_PATH = "/"
